services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: dev
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/var/www/html/'
      - './docker/php/php.ini:/usr/local/etc/php/php.ini:ro'
      - './.composer:/.composer'

  nginx:
    image: nginx:stable
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - '.:/var/www/html/'
      - './docker/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro'

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    stop_grace_period: 3s
    volumes:
      - './:/usr/src/app'

volumes:
  x-mysql:
    driver: local
  x-redis:
    driver: local
